### ISSUE TITLE
Apple privacy manifest support

### ISSUE THREAD

**Issue by pavm035** [rakuten-ads/Rakuten-Reward-Native-iOS#10]
Hi,

As per apple announcment regarding privacy manifest support, is there any support from on this SDK to provide manifest file and signing the xcframework

https://developer.apple.com/news/?id=3d8a9yyh
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by 21DerickDerick** [comment]
Hi, we have released new version with Privacy manifest support. Can please try https://github.com/rakuten-ads/Rakuten-Reward-Native-iOS/releases/tag/6.3.0? thanks

**Comment by pavm035** [comment]
@21DerickDerick  Thanks for the update, with this release is SDK signed as well?

**Comment by 21DerickDerick** [comment]
Yes, it's codesign already. Thanks for waiting!
