### ISSUE TITLE
SDK not compatible with Xcode Simulator on M1 Macs

### ISSUE THREAD

**Issue by ChristopherDrum** [rakuten-ads/Rakuten-Reward-Native-iOS#5]
The included Simulator framework does not have arm support and so cannot build and link for M1-based simulators.
Results in project source code that references the SDK failing to build with errors
`Cannot find Mission in scope.` (and other Rakuten-based objects and methods)

Running Xcode in Rosetta mode works.
But it is frustrating to be denied a native M1 Xcode build-and-test just because of this one SDK.

**Comment by 21DerickDerick** [comment]
Sorry late reply. M1 is supported starting from version 3.4.3
