### ISSUE TITLE
Display ADBanner belike rakuten-reward-iOS

### ISSUE THREAD

**Issue by pqv2210** [rakuten-ads/Rakuten-Reward-Native-iOS#9]
Reference from [Add RakutenADBannerView to storyboard](https://github.com/RakutenReward/RakutenRewardSDK/wiki/%E6%A5%BD%E5%A4%A9%E3%83%AA%E3%83%AF%E3%83%BC%E3%83%89SDK-iOS-Ad-%E6%A9%9F%E8%83%BD#rakutenadbannerview-%E3%82%92-storyboard%E3%81%AB%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B).
I need display a banner belike that document and i was researched but i don't see any method to display ADBanner in this document.
How can i use ADBanner in Rakuten Reward Native SDK?
Do i need to use https://github.com/rakuten-ads/Rakuten-Ads-iOS?

**Comment by 21DerickDerick** [comment]
Sorry for the late reply. We are from the Mission/Reward SDK team

RakutenRewardNative SDK does not support the ADSDK API.

The RakutenADBannerView reference that you mentioned is from this SDK: https://github.com/Rakuten-Reward-SDK/Reward-SDK-iOS

[RUNA SDK](https://github.com/rakuten-ads/Rakuten-Ads-iOS) is from the RUNA team. It's a separate team than us.

**Comment by pqv2210** [comment]
@21DerickDerick Thanks for your reply. I resolved my problem. :D
